# knowledge_base/ipc_sections.py

IPC_SECTIONS = [
    {
        "section": "299",
        "title": "Culpable Homicide",
        "description": "Causing death intentionally or with knowledge that death is likely",
        "punishment": "Life imprisonment or up to 10 years + fine",
        "keywords": ["death", "kill", "killed", "homicide", "dead", "died"],
    },
    {
        "section": "300",
        "title": "Murder",
        "description": "Intentional killing with premeditation",
        "punishment": "Death or life imprisonment + fine",
        "keywords": ["murder", "killed", "kill", "stabbed", "shot", "dead", "poisoned"],
    },
    {
        "section": "307",
        "title": "Attempt to Murder",
        "description": "Attempting to commit murder",
        "punishment": "Up to 10 years + fine",
        "keywords": ["attempt", "tried to kill", "attack", "knife", "gun", "weapon"],
    },
    {
        "section": "323",
        "title": "Voluntarily Causing Hurt",
        "description": "Intentionally causing bodily pain or injury",
        "punishment": "Up to 1 year or fine",
        "keywords": ["hurt", "pain", "injury", "beat", "slap", "punch", "kick", "hit"],
    },
    {
        "section": "324",
        "title": "Causing Hurt by Dangerous Weapon",
        "description": "Causing hurt using weapons or fire",
        "punishment": "Up to 3 years or fine",
        "keywords": ["knife", "rod", "weapon", "blade", "cut", "stab", "fire"],
    },
    {
        "section": "354",
        "title": "Assault on Woman",
        "description": "Assault or criminal force to outrage modesty of woman",
        "punishment": "1 to 5 years + fine",
        "keywords": ["woman", "female", "molest", "grope", "modesty", "eve tease"],
    },
    {
        "section": "375",
        "title": "Rape",
        "description": "Sexual intercourse without consent",
        "punishment": "Min 7 years, may extend to life",
        "keywords": ["rape", "sexual assault", "consent", "forced", "violated"],
    },
    {
        "section": "378",
        "title": "Theft",
        "description": "Dishonestly taking movable property out of possession of any person",
        "punishment": "Up to 3 years or fine",
        "keywords": ["stolen", "theft", "steal", "missing", "pickpocket", "wallet", "phone", "bag"],
    },
    {
        "section": "380",
        "title": "Theft in Dwelling House",
        "description": "Theft in any building used as a dwelling or for worship",
        "punishment": "Up to 7 years + fine",
        "keywords": ["house", "home", "burglary", "break in", "entered", "night"],
    },
    {
        "section": "392",
        "title": "Robbery",
        "description": "Theft or extortion with force, threat or wrongful restraint",
        "punishment": "Up to 10 years + fine",
        "keywords": ["robbery", "robbed", "snatched", "force", "threatened", "mugged", "looted", "chain"],
    },
    {
        "section": "395",
        "title": "Dacoity",
        "description": "Robbery committed by five or more persons",
        "punishment": "Life imprisonment or up to 10 years + fine",
        "keywords": ["gang", "group", "multiple", "dacoity", "mob", "looted"],
    },
    {
        "section": "406",
        "title": "Criminal Breach of Trust",
        "description": "Dishonest misappropriation of property entrusted",
        "punishment": "Up to 3 years or fine",
        "keywords": ["trust", "entrusted", "misappropriate", "embezzle", "withheld", "misused"],
    },
    {
        "section": "420",
        "title": "Cheating",
        "description": "Cheating and dishonestly inducing delivery of property",
        "punishment": "Up to 7 years + fine",
        "keywords": ["cheat", "fraud", "scam", "deceive", "fake", "trick", "upi", "online fraud", "investment"],
    },
    {
        "section": "427",
        "title": "Mischief Causing Damage",
        "description": "Mischief causing damage to property",
        "punishment": "Up to 2 years or fine",
        "keywords": ["damage", "destroy", "vandal", "broke", "smashed", "vehicle", "car"],
    },
    {
        "section": "447",
        "title": "Criminal Trespass",
        "description": "Entering or remaining on property without permission",
        "punishment": "Up to 3 months or fine",
        "keywords": ["trespass", "entered", "unauthorized", "without permission", "intruded"],
    },
    {
        "section": "498A",
        "title": "Cruelty by Husband or Relatives",
        "description": "Husband or relative subjecting woman to cruelty",
        "punishment": "Up to 3 years + fine",
        "keywords": ["husband", "domestic", "cruelty", "harassment", "dowry", "wife", "in-laws", "marital"],
    },
    {
        "section": "503",
        "title": "Criminal Intimidation",
        "description": "Threatening another with injury to cause alarm or compel action",
        "punishment": "Up to 2 years or fine",
        "keywords": ["threat", "threaten", "intimidate", "scare", "blackmail", "pressure", "warned", "fear"],
    },
    {
        "section": "506",
        "title": "Punishment for Criminal Intimidation",
        "description": "Punishment for threatening death or grievous hurt",
        "punishment": "Up to 7 years + fine",
        "keywords": ["death threat", "kill threat", "threaten to kill", "threatened with weapon"],
    },
    {
        "section": "509",
        "title": "Insult Modesty of Woman",
        "description": "Uttering words or making gestures to insult modesty of a woman",
        "punishment": "Up to 3 years + fine",
        "keywords": ["insult", "gesture", "obscene", "remark", "harassment", "stalking", "woman"],
    },
]