"""
Indian Penal Code (IPC) Sections Database
==========================================

Comprehensive database of commonly used IPC sections
relevant to FIR generation.
"""

IPC_SECTIONS = [
    # Crimes Against Person - Death/Homicide
    {
        "section": "299",
        "title": "Culpable Homicide",
        "description": "Causing death intentionally or with knowledge that death is likely",
        "punishment": "Life imprisonment or up to 10 years + fine",
        "keywords": ["death", "kill", "killed", "homicide", "dead", "died", "accidental"],
        "category": "Crime Against Person",
    },
    {
        "section": "300",
        "title": "Murder",
        "description": "Intentional killing with premeditation and knowledge",
        "punishment": "Death or life imprisonment + fine",
        "keywords": ["murder", "killed", "kill", "stabbed", "shot", "dead", "poisoned", "premeditated"],
        "category": "Crime Against Person",
    },
    {
        "section": "302",
        "title": "Punishment for Murder",
        "description": "Punishment provision for murder conviction",
        "punishment": "Death or life imprisonment",
        "keywords": ["murder", "death", "execution"],
        "category": "Crime Against Person",
    },
    {
        "section": "304",
        "title": "Death by Negligence",
        "description": "Death caused by act done rashly or negligently",
        "punishment": "Up to 6 months or fine + 2 years",
        "keywords": ["negligence", "accident", "rash", "careless", "death"],
        "category": "Crime Against Person",
    },
    {
        "section": "307",
        "title": "Attempt to Murder",
        "description": "Attempting to commit murder",
        "punishment": "Up to 10 years + fine",
        "keywords": ["attempt", "tried to kill", "attack", "knife", "gun", "weapon", "stabbed"],
        "category": "Crime Against Person",
    },
    
    # Crimes Against Person - Hurt/Injury
    {
        "section": "323",
        "title": "Voluntarily Causing Hurt",
        "description": "Intentionally causing bodily pain or injury without weapon",
        "punishment": "Up to 1 year or fine",
        "keywords": ["hurt", "pain", "injury", "beat", "slap", "punch", "kick", "hit", "assault"],
        "category": "Crime Against Person",
    },
    {
        "section": "324",
        "title": "Causing Hurt by Weapon",
        "description": "Causing hurt using weapons, dangerous objects or fire",
        "punishment": "Up to 3 years + fine",
        "keywords": ["knife", "rod", "weapon", "blade", "cut", "stab", "fire", "burn", "armed"],
        "category": "Crime Against Person",
    },
    {
        "section": "325",
        "title": "Voluntarily Causing Grievous Hurt",
        "description": "Causing eight types of hurt: emasculation, loss of limb, sight, hearing, etc.",
        "punishment": "Up to 7 years + fine",
        "keywords": ["grievous", "serious injury", "wound", "permanent", "disability", "fracture"],
        "category": "Crime Against Person",
    },
    {
        "section": "326",
        "title": "Causing Grievous Hurt by Weapon",
        "description": "Causing grievous hurt with dangerous weapons or objects",
        "punishment": "Up to 10 years + fine",
        "keywords": ["grievous", "weapon", "acid", "corrosive", "burn", "severe injury"],
        "category": "Crime Against Person",
    },
    {
        "section": "337",
        "title": "Causing Hurt by Act Endangering Life",
        "description": "Causing hurt by act endangering human life",
        "punishment": "Up to 6 months or fine",
        "keywords": ["endangering life", "rash", "negligent", "hurt"],
        "category": "Crime Against Person",
    },
    {
        "section": "338",
        "title": "Causing Grievous Hurt by Act Endangering Life",
        "description": "Causing grievous hurt by act endangering life",
        "punishment": "Up to 2 years or fine",
        "keywords": ["endangering", "grievous", "negligent", "rash"],
        "category": "Crime Against Person",
    },
    
    # Sexual Offences
    {
        "section": "354",
        "title": "Assault or Endangering Modesty of Woman",
        "description": "Using criminal force to outrage modesty of woman",
        "punishment": "Up to 3 years + fine",
        "keywords": ["woman", "female", "molest", "grope", "modesty", "eve tease", "touch"],
        "category": "Sexual Offence",
    },
    {
        "section": "354-A",
        "title": "Sexual Harassment",
        "description": "Unwelcome conduct of sexual nature constituting harassment",
        "punishment": "Up to 3 years + fine",
        "keywords": ["harassment", "sexual", "workplace", "unwanted", "advances"],
        "category": "Sexual Offence",
    },
    {
        "section": "375",
        "title": "Rape",
        "description": "Sexual intercourse by man with woman without consent or with knowledge",
        "punishment": "Minimum 7 years, may extend to life + fine",
        "keywords": ["rape", "sexual assault", "consent", "forced", "intercourse", "violated"],
        "category": "Sexual Offence",
    },
    {
        "section": "376",
        "title": "Punishment for Rape",
        "description": "Punishment provisions for rape conviction",
        "punishment": "7 to 10 years or life imprisonment + fine",
        "keywords": ["rape", "punishment", "victim", "justice"],
        "category": "Sexual Offence",
    },
    {
        "section": "509",
        "title": "Insulting Modesty of Woman",
        "description": "Insulting the modesty of a person through words, sounds, gestures",
        "punishment": "Up to 3 years or fine",
        "keywords": ["insult", "modesty", "woman", "abusive", "derogatory"],
        "category": "Sexual Offence",
    },
    
    # Theft & Related Offences
    {
        "section": "378",
        "title": "Theft",
        "description": "Dishonestly taking movable property without owner's consent",
        "punishment": "Up to 3 years + fine",
        "keywords": ["stolen", "theft", "steal", "missing", "pickpocket", "shoplifting"],
        "category": "Theft & Property Crime",
    },
    {
        "section": "379",
        "title": "Punishment for Theft",
        "description": "Punishment provision for theft conviction",
        "punishment": "Up to 3 years + fine",
        "keywords": ["theft", "stolen", "punishment", "penalty"],
        "category": "Theft & Property Crime",
    },
    {
        "section": "380",
        "title": "Theft in Dwelling House",
        "description": "Theft in any building used as dwelling or for worship",
        "punishment": "Up to 7 years + fine",
        "keywords": ["house", "home", "burglary", "break in", "entered", "night", "dwelling"],
        "category": "Theft & Property Crime",
    },
    {
        "section": "381",
        "title": "Theft by Servant",
        "description": "Theft committed by servant or member of household",
        "punishment": "Up to 7 years + fine",
        "keywords": ["servant", "employee", "household", "trusted", "insider theft"],
        "category": "Theft & Property Crime",
    },
    {
        "section": "382",
        "title": "Theft after preparation for Dacoity",
        "description": "Theft after preparation for committing dacoity",
        "punishment": "Up to 10 years + fine",
        "keywords": ["gang", "organized", "multiple", "premeditated"],
        "category": "Theft & Property Crime",
    },
    {
        "section": "392",
        "title": "Robbery",
        "description": "Theft with force, threat or wrongful restraint",
        "punishment": "Up to 10 years + fine",
        "keywords": ["robbery", "robbed", "snatched", "force", "threatened", "mugged", "looted"],
        "category": "Theft & Property Crime",
    },
    {
        "section": "395",
        "title": "Dacoity",
        "description": "Robbery committed by five or more persons",
        "punishment": "Life imprisonment or up to 10 years + fine",
        "keywords": ["gang", "group", "multiple", "dacoity", "mob", "looted", "five persons"],
        "category": "Theft & Property Crime",
    },
    
    # Criminal Breach of Trust & Fraud
    {
        "section": "406",
        "title": "Criminal Breach of Trust",
        "description": "Dishonest misappropriation of property entrusted to person",
        "punishment": "Up to 3 years or fine",
        "keywords": ["breach of trust", "misappropriate", "entrusted", "dishonest"],
        "category": "Fraud & Trust",
    },
    {
        "section": "419",
        "title": "Cheating",
        "description": "Intentionally deceiving by false representation",
        "punishment": "Up to 1 year or fine",
        "keywords": ["cheat", "fraud", "deceive", "false", "deception", "scam"],
        "category": "Fraud & Trust",
    },
    {
        "section": "420",
        "title": "Cheating and Dishonestly Inducing",
        "description": "Cheating and dishonestly inducing delivery of property",
        "punishment": "Up to 7 years + fine",
        "keywords": ["cheating", "fraud", "induced", "money", "property"],
        "category": "Fraud & Trust",
    },
    
    # Threats & Intimidation
    {
        "section": "503",
        "title": "Criminal Intimidation",
        "description": "Threatening any injury to person, property or reputation",
        "punishment": "Up to 2 years or fine",
        "keywords": ["threat", "threaten", "intimidate", "menace", "scare"],
        "category": "Threat & Intimidation",
    },
    {
        "section": "504",
        "title": "Insult with Intent to Provoke Breach",
        "description": "Insulting remarks intended to provoke breach of peace",
        "punishment": "Up to 2 years or fine",
        "keywords": ["insult", "provoke", "breach", "violence"],
        "category": "Threat & Intimidation",
    },
    {
        "section": "506",
        "title": "Criminal Intimidation by Anonymous Communication",
        "description": "Threatening by anonymous letter or communication",
        "punishment": "Up to 2 years or fine",
        "keywords": ["threat", "anonymous", "blackmail", "extort", "intimidate"],
        "category": "Threat & Intimidation",
    },
    
    # Domestic Violence & Family
    {
        "section": "498-A",
        "title": "Cruelty by Husband or In-laws",
        "description": "Cruelty by husband or in-laws driving woman to suicide",
        "punishment": "Up to 3 years + fine",
        "keywords": ["cruelty", "domestic", "dowry", "in-laws", "harassment", "torture"],
        "category": "Domestic Violence",
    },
    {
        "section": "304-B",
        "title": "Dowry Death",
        "description": "Death of a woman caused by any burns or bodily injury",
        "punishment": "Up to 7 years + fine",
        "keywords": ["dowry", "death", "bride", "burning"],
        "category": "Domestic Violence",
    },
    
    # Property Damage
    {
        "section": "425",
        "title": "Mischief",
        "description": "Intentional or reckless causing loss or damage",
        "punishment": "Up to 3 months or fine",
        "keywords": ["mischief", "damage", "destroy", "vandal"],
        "category": "Property Crime",
    },
    {
        "section": "426",
        "title": "Punishment for Mischief",
        "description": "General punishment for mischief",
        "punishment": "Up to 3 months or fine",
        "keywords": ["mischief", "damage", "punishment"],
        "category": "Property Crime",
    },
    {
        "section": "427",
        "title": "Mischief Causing Damage",
        "description": "Mischief causing damage over 50 rupees",
        "punishment": "Up to 6 months or fine",
        "keywords": ["damage", "destroyed", "property", "vandalism"],
        "category": "Property Crime",
    },
    
    # Cybercrime
    {
        "section": "66",
        "title": "Hacking Computer Systems",
        "description": "Unauthorized access to computer systems",
        "punishment": "Up to 3 years + fine",
        "keywords": ["hacking", "cyber", "unauthorized", "access", "computer"],
        "category": "Cybercrime",
    },
    {
        "section": "66-B",
        "title": "Dishonestly Receiving Stolen Data",
        "description": "Receiving stolen or illegally obtained computer resource",
        "punishment": "Up to 3 years + fine",
        "keywords": ["data", "stolen", "cyber", "illegal"],
        "category": "Cybercrime",
    },
    {
        "section": "66-C",
        "title": "Identity Theft",
        "description": "Fraudulently using another person's digital signature",
        "punishment": "Up to 3 years + fine",
        "keywords": ["identity", "fraud", "cyber", "signature"],
        "category": "Cybercrime",
    },
    {
        "section": "66-D",
        "title": "Online Cheating",
        "description": "Cheating by personation on Internet",
        "punishment": "Up to 3 years + fine",
        "keywords": ["online", "phishing", "fraud", "scam", "impersonation"],
        "category": "Cybercrime",
    },
    {
        "section": "406",
        "title": "Criminal Breach of Trust",
        "description": "Dishonest misappropriation of property entrusted",
        "punishment": "Up to 3 years or fine",
        "keywords": ["trust", "entrusted", "misappropriate", "embezzle", "withheld", "misused"],
    },
    {
        "section": "420",
        "title": "Cheating",
        "description": "Cheating and dishonestly inducing delivery of property",
        "punishment": "Up to 7 years + fine",
        "keywords": ["cheat", "fraud", "scam", "deceive", "fake", "trick", "upi", "online fraud", "investment"],
    },
    {
        "section": "427",
        "title": "Mischief Causing Damage",
        "description": "Mischief causing damage to property",
        "punishment": "Up to 2 years or fine",
        "keywords": ["damage", "destroy", "vandal", "broke", "smashed", "vehicle", "car"],
    },
    {
        "section": "447",
        "title": "Criminal Trespass",
        "description": "Entering or remaining on property without permission",
        "punishment": "Up to 3 months or fine",
        "keywords": ["trespass", "entered", "unauthorized", "without permission", "intruded"],
    },
    {
        "section": "498A",
        "title": "Cruelty by Husband or Relatives",
        "description": "Husband or relative subjecting woman to cruelty",
        "punishment": "Up to 3 years + fine",
        "keywords": ["husband", "domestic", "cruelty", "harassment", "dowry", "wife", "in-laws", "marital"],
    },
    {
        "section": "503",
        "title": "Criminal Intimidation",
        "description": "Threatening another with injury to cause alarm or compel action",
        "punishment": "Up to 2 years or fine",
        "keywords": ["threat", "threaten", "intimidate", "scare", "blackmail", "pressure", "warned", "fear"],
    },
    {
        "section": "506",
        "title": "Punishment for Criminal Intimidation",
        "description": "Punishment for threatening death or grievous hurt",
        "punishment": "Up to 7 years + fine",
        "keywords": ["death threat", "kill threat", "threaten to kill", "threatened with weapon"],
    },
    {
        "section": "509",
        "title": "Insult Modesty of Woman",
        "description": "Uttering words or making gestures to insult modesty of a woman",
        "punishment": "Up to 3 years + fine",
        "keywords": ["insult", "gesture", "obscene", "remark", "harassment", "stalking", "woman"],
    },
]